# fly.toml app configuration file generated for solitary-pond-9861 on 2023-05-08T10:41:03Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "solitary-pond-9861"
primary_region = "nrt"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[[statics]]
  guest_path = "/rails/public"
  url_prefix = "/"
